name: brillo_connetz_app
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

  cupertino_icons: ^1.0.2
  http: ^0.13.3
  provider: ^6.0.2
  google_fonts: ^2.2.0
  page_transition: ^2.0.4
  shared_preferences: ^2.0.7
  flutter_screenutil: ^5.0.3
  pinput: ^1.2.2
  awesome_card: ^1.1.6
  fluttertoast: ^8.0.8
  flutter_dotenv: ^5.0.2
  flutter_paystack: ^1.0.5+1
  flutter_svg: ^0.22.0
  sticky_headers: ^0.2.0
  country_code_picker: ^2.0.2
  connectivity_plus: ^2.1.0
  internet_connection_checker: ^0.0.1+3
  font_awesome_flutter: ^9.2.0
  image_picker: ^0.8.4+9
  cloudinary_public: ^0.11.0
  flutter_staggered_grid_view: ^0.6.1
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  generate: true

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - .env